# Generated by Django 5.2.1 on 2025-07-03 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esercizio',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gruppo_allenante', models.CharField(blank=True, choices=[('petto', 'Petto'), ('spalle', 'Spalle'), ('bicipiti', 'Bicipiti'), ('tricipiti', 'Tricipiti'), ('quadricipiti', 'Quadricipiti'), ('femorali', 'Femorali'), ('addominali', 'Addominali'), ('schiena', 'Schiena'), ('polpacci', 'Polpacci')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Integratore',
            fields=[
                ('nome_integratore', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('dosaggio', models.DecimalField(blank=True, decimal_places=2, help_text='Dosaggio giornaliero in grammi', max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('stipendio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('certificazione', models.ImageField(blank=True, null=True, upload_to='certificazioni/')),
                ('tipo_sport', models.CharField(blank=True, max_length=100, null=True)),
                ('data_iscrizione', models.DateField(blank=True, null=True)),
                ('scadenza_abbonamento', models.DateField(blank=True, null=True)),
                ('stato_abbonamento', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheda_integratori',
            fields=[
                ('id_scheda_integratori', models.AutoField(primary_key=True, serialize=False)),
                ('email_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integratori', to='FitStats.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Scheda',
            fields=[
                ('id_scheda', models.IntegerField(primary_key=True, serialize=False)),
                ('giorno_inizio', models.DateField()),
                ('giorno_fine', models.DateField()),
                ('creata_da', models.CharField(max_length=100)),
                ('email_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schede', to='FitStats.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Composizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_PT', models.IntegerField(blank=True, default=0, null=True)),
                ('tempo_recupero', models.IntegerField(blank=True, default=60, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('ripetizioni', models.IntegerField(blank=True, default=0, null=True)),
                ('nome_giornata', models.CharField(default='', max_length=100)),
                ('nome_esercizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composizioni', to='FitStats.esercizio')),
                ('scheda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composizioni', to='FitStats.scheda')),
            ],
            options={
                'unique_together': {('scheda', 'nome_esercizio')},
            },
        ),
        migrations.CreateModel(
            name='Unione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_integratore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unioni', to='FitStats.integratore')),
                ('scheda_integratori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unioni', to='FitStats.scheda_integratori')),
            ],
            options={
                'unique_together': {('scheda_integratori', 'nome_integratore')},
            },
        ),
        migrations.CreateModel(
            name='Preferenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_esercizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferenze', to='FitStats.esercizio')),
                ('email_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferenze', to='FitStats.utente')),
            ],
            options={
                'unique_together': {('nome_esercizio', 'email_utente')},
            },
        ),
    ]
