# Generated by Django 5.2.1 on 2025-07-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitStats', '0002_alter_scheda_id_scheda'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='composizione',
            unique_together={('scheda', 'nome_giornata', 'nome_esercizio')},
        ),
    ]
