# Generated by Django 5.2.1 on 2025-06-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitStats', '0004_composizione_esercizio_integratore_preferenza_scheda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esercizio',
            name='serie_PT',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
