# Generated by Django 5.2.1 on 2025-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitStats', '0005_alter_esercizio_serie_pt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='certificazione',
            field=models.ImageField(blank=True, null=True, upload_to='certificazioni/'),
        ),
    ]
