# Generated by Django 5.2.1 on 2025-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitStats', '0006_alter_utente_certificazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esercizio',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='esercizio',
            name='tempo_recupero',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
