# Generated by Django 5.2.1 on 2025-07-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitStats', '0007_alter_esercizio_peso_alter_esercizio_tempo_recupero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esercizio',
            name='ripetizioni',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
