# Generated by Django 5.2.1 on 2025-07-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitStats', '0008_alter_esercizio_ripetizioni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esercizio',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='esercizio',
            name='ripetizioni',
        ),
        migrations.RemoveField(
            model_name='esercizio',
            name='serie_PT',
        ),
        migrations.RemoveField(
            model_name='esercizio',
            name='tempo_recupero',
        ),
        migrations.AddField(
            model_name='composizione',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composizione',
            name='ripetizioni',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='composizione',
            name='serie_PT',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='composizione',
            name='tempo_recupero',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
