# Generated by Django 5.2.1 on 2025-07-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitStats', '0009_remove_esercizio_peso_remove_esercizio_ripetizioni_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='composizione',
            unique_together={('scheda', 'nome_esercizio')},
        ),
    ]
